name = "Gclib"
uuid = "34b9e73c-8a29-4cd8-bcc0-ee7fe2217527"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]
version = "0.1.3"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"

[compat]
CEnum = "0.4.2"
